name: 🖥️ Launch Private Ubuntu RDP VM (via Tailscale)

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Connect to Tailscale
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-actions-rdp
      env:
        # Pipe the output of 'tailscale ip' to a file for the next step
        TAILSCALE_IP_CMD: "sudo tailscale ip -4"

    - name: Get Tailscale IP
      id: get_ip
      run: |
        # Sleep for a moment to ensure Tailscale is fully connected and has an IP
        sleep 5
        echo "TAILSCALE_IP=$(sudo tailscale ip -4)" >> $GITHUB_OUTPUT

    - name: Install XFCE4 and XRDP
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xrdp
        sudo systemctl enable xrdp
        echo xfce4-session > ~/.xsession
        sudo cp ~/.xsession /etc/skel
        sudo service xrdp restart

    - name: Generate RDP Password
      run: |
        # Generate a random strong password
        password=$(openssl rand -base64 15)
        echo "ubuntu:$password" | sudo chpasswd
        # Store the password in a GitHub environment file
        echo "RDP_PASSWORD=$password" >> $GITHUB_ENV
        echo "🟢 RDP Password has been set."

    - name: Display Connection Information
      run: |
        echo "========================================"
        echo "          RDP VM is Ready!              "
        echo "========================================"
        echo "🌐 Connect using your RDP client to:"
        echo "   Address: ${{ steps.get_ip.outputs.TAILSCALE_IP }}"
        echo "   Username: ubuntu"
        echo "   Password: ${{ env.RDP_PASSWORD }}"
        echo "========================================"
        echo "🔒 Secure: This VM is ONLY accessible via your private Tailscale network."
        echo "⚠️  Temporary: This VM will self-destruct in ~6 hours."
        echo "========================================"

    - name: Keep alive
      run: sleep 4000 # Max time allowed
